version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/html/wf-login
    networks:
      - local_network
  php:
    container_name: php
    build: ./
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/wf-login
    networks:
      - local_network
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - local_network

volumes:
  mysql-volume: { }

networks:
  local_network: { }